version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - PORT=3001
      - NODE_ENV=production
    ports:
      - "3001:3001"
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
