version: '2'
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${{Postgres.DATABASE_URL}}
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=7d
      - PORT=3001
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=${{Backend.RAILWAY_PUBLIC_DOMAIN}}
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=rfp_management
      - POSTGRES_USER=rfp_user
      - POSTGRES_PASSWORD=rfp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
